# Generated by Django 6.0.6 on 2026-07-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_counted_view_post_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='counted_view',
            field=models.IntegerField(default=0),
        ),
    ]
